name: LaTeX build (latex-action)

on:
  push:
    paths:
      - 'consolidation_project/**.tex'
      - '.github/workflows/latex_build.yml'
  pull_request:
    paths:
      - 'consolidation_project/**.tex'
      - '.github/workflows/latex_build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile with LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            consolidation_project/ubt_core_main.tex
          pre_compile: |
            tlmgr update --self
            tlmgr install pgf pgfplots xcolor cm-super
          latexmk_shell_escape: true

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            **/*.pdf
            !**/node_modules/**
            !**/.git/**
