name: LaTeX – build all PDFs

on:
  push:
  pull_request:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      roots: ${{ steps.discover.outputs.roots }}
    steps:
      - uses: actions/checkout@v4

      - id: discover
        name: Discover LaTeX roots
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t roots < <(git ls-files '*.tex' \
            | grep -Ev '^(vendor|node_modules|build|out|dist)/' \
            | xargs -r grep -l -E '\\documentclass')
          if [ ${#roots[@]} -eq 0 ]; then
            echo "roots=[]" >> "$GITHUB_OUTPUT"
          else
            printf '%s\n' "${roots[@]}" \
              | jq -R -s -c 'split("\n")[:-1]' \
              | sed 's/^/roots=/' >> "$GITHUB_OUTPUT"
          fi

  compile:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        root: ${{ fromJson(needs.discover.outputs.roots) }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect engine + paths
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          root="${{ matrix.root }}"
          dir="$(dirname "$root")"
          pdf="${root%.tex}.pdf"
          engine="pdflatex"
          grep -Eq '^[[:space:]]*%!?TEX.*xelatex' "$root" && engine="xelatex"
          grep -Eq '^[[:space:]]*%!?TEX.*lualatex' "$root" && engine="lualatex"
          grep -Eq '\\usepackage\{(fontspec|polyglossia|unicode-math)\}' "$root" && engine="xelatex"
          grep -Eq '\\usepackage\{(luacode|luaotfload)\}' "$root" && engine="lualatex"
          safe="${root//\//__}"; safe="${safe// /_}"
          {
            echo "dir=$dir"
            echo "pdf=$pdf"
            echo "engine=$engine"
            echo "safe=$safe"
            echo "sha=${GITHUB_SHA::7}"
          } >> "$GITHUB_OUTPUT"

      - name: LaTeX build ${{ matrix.root }}
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ matrix.root }}
          work_in_root_file_dir: true
          continue_on_error: true
          # nepoužíváme `compiler`!
          latexmk_use_xelatex: ${{ steps.detect.outputs.engine == 'xelatex' }}
          latexmk_use_lualatex: ${{ steps.detect.outputs.engine == 'lualatex' }}
          pre_compile: |
            set -e
            tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet || true
            tlmgr update --self || true
            tlmgr install \
              collection-latexrecommended collection-fontsrecommended collection-bibtexextra \
              graphics hyperref geometry xcolor cm-super \
              amsmath amsfonts mathtools siunitx physics \
              etoolbox babel csquotes biblatex biber url soul \
              pgf pgfplots tikz-cd standalone float caption \
              todonotes wrapfig mhchem ifmtarg kvoptions listings fancyvrb pdftexcmds kvsetkeys \
              fontspec unicode-math polyglossia || true
            tlmgr update --all || true

      - name: Upload PDF (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pdf-${{ steps.detect.outputs.safe }}-${{ steps.detect.outputs.sha }}
          path: ${{ steps.detect.outputs.pdf }}
          if-no-files-found: ignore

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ steps.detect.outputs.safe }}-${{ steps.detect.outputs.sha }}
          path: |
            ${{ steps.detect.outputs.dir }}/*.log
            ${{ steps.detect.outputs.dir }}/*.blg
            ${{ steps.detect.outputs.dir }}/*.fls
            ${{ steps.detect.outputs.dir }}/*.aux
          if-no-files-found: ignore

