name: LaTeX – build all roots

on:
  push:
  pull_request:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      roots: ${{ steps.discover.outputs.roots }}
    steps:
      - uses: actions/checkout@v4

      - id: discover
        name: Discover LaTeX roots
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t roots < <(git ls-files '*.tex' \
            | grep -Ev '^(vendor|node_modules|build|out|dist)/' \
            | xargs -r grep -l -E '\\documentclass')
          if [ ${#roots[@]} -eq 0 ]; then
            echo 'roots=[]' >> "$GITHUB_OUTPUT"
          else
            printf '%s\n' "${roots[@]}" \
              | jq -R -s -c 'split("\n")[:-1]' \
              | sed 's/^/roots=/' >> "$GITHUB_OUTPUT"
          fi

  compile:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        root: ${{ fromJson(needs.discover.outputs.roots) }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute PDF path
        id: pdf
        shell: bash
        run: |
          pdf="${{ matrix.root }}"
          pdf="${pdf%.tex}.pdf"
          echo "path=$pdf" >> "$GITHUB_OUTPUT"

      - name: LaTeX build ${{ matrix.root }}
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ matrix.root }}
          continue_on_error: true
          pre_compile: |
            tlmgr update --self
            tlmgr install cm-super xcolor pgf pgfplots slashed

      - name: Upload PDF ${{ matrix.root }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pdf-${{ matrix.root }}
          path: ${{ steps.pdf.outputs.path }}

