name: Compile all .tex to local PDF folders

on:
  push:
    paths:
      - '**/*.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # nutné pro push přes GITHUB_TOKEN

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Install full LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile all .tex files and move PDFs to subfolders
      run: |
        find . -name "*.tex" | while read texfile; do
          dir=$(dirname "$texfile")
          base=$(basename "$texfile" .tex)
          mkdir -p "$dir/pdf"
          pdflatex -interaction=nonstopmode -output-directory "$dir/pdf" "$texfile" || true
        done

    - name: Commit generated PDFs
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        shopt -s globstar
        git add **/pdf/*.pdf || true
        git commit -m "Auto-generated PDFs [ci skip]" || echo "No changes to commit"
        git push

