\
name: Build all LaTeX PDFs

on:
  push:
    paths:
      - "**.tex"
      - ".github/workflows/latex-build-all.yml"
      - "scripts/find-tex-roots.sh"
      - "**.bib"
      - "**.sty"
      - "**.cls"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.pdf"
      - "**.eps"
  pull_request:
    paths:
      - "**.tex"
      - ".github/workflows/latex-build-all.yml"
      - "scripts/find-tex-roots.sh"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: List TeX roots
        id: roots
        run: |
          chmod +x scripts/find-tex-roots.sh || true
          scripts/find-tex-roots.sh > tex_roots.txt || true
          echo "Found TeX roots:"
          cat tex_roots.txt || true

      - name: Build JSON matrix
        id: collect
        run: |
          if [ ! -s tex_roots.txt ]; then
            echo 'matrix={"file":[]}' >> "$GITHUB_OUTPUT"
          else
            printf 'matrix={"file":[' >> "$GITHUB_OUTPUT"
            paste -sd, tex_roots.txt | sed 's~[^,][^,]*~"&"~g' >> "$GITHUB_OUTPUT"
            printf ']}\n' >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: discover
    if: ${{ fromJson(needs.discover.outputs.matrix).file && fromJson(needs.discover.outputs.matrix).file != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up TeX Live and compile
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.file }}
          latexmk_use_lualatex: false
          latexmk_shell_escape: true
          extra_system_packages: "ghostscript"
          work_in_root_file_dir: true

      - name: Upload PDFs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            **/*.pdf
          if-no-files-found: warn
