name: LaTeX build (all)

on:
  push:
    paths:
      - '**/*.tex'
      - '.github/workflows/latex-build-all.yml'
  pull_request:
    paths:
      - '**/*.tex'
      - '.github/workflows/latex-build-all.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use a full TeX Live environment and run custom commands (robust for multi-doc repos)
      - name: Set up TeX Live and compile all .tex with \begin{document}
        uses: xu-cheng/texlive-action@v3
        with:
          run: |
            set -euo pipefail
            shopt -s globstar nullglob
            # Find only root documents (those containing \begin{document})
            mapfile -t TEXFILES < <(grep -rl --include='*.tex' '\begin{document}' . | sort)
            echo "Found ${#TEXFILES[@]} root documents:"
            printf ' - %s
' "${TEXFILES[@]}"
            for f in "${TEXFILES[@]}"; do
              echo "::group::Building $f"
              latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -cd "$f"
              echo "::endgroup::"
            done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            **/*.pdf
            !**/node_modules/**
            !**/.git/**
